/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"
export interface Story {
  intro: string
  stage_descriptions: string[]
  good_ending: string
  bad_ending: string
  
}

export interface StoryParams {
  theme: string
  difficulty: string
  stage_physical_descriptions: string[]
  num_players: number
  time_limit_min: number
  
}
